### ISSUE TITLE
Resque restart on deployment

### ISSUE THREAD

**Issue by hectorcorrea** [psu-stewardship/archivesphere#143] opened 2015-08-25 20:24 UTC
With the current cap task resque is not restarted properly after a deployment. This means that jobs might execute with an outdated version of the code. 

The issue might be the `init` script for resque. @awead suggested looking at the "with shutdown" option or something like that.

**Comment by awead** [comment] 2015-08-26 13:29
I can't reproduce this, so I'm closing for now.

**Closed by awead** 2015-08-26 13:29 UTC
